In [1]:
## Description:
## Extraction some candelstick patterns from data frame provided by yfinance
## It filters the data frame and print days that the pattern is recognized
## it added Engulfing (CDLENGULFING) pattern recognition into the data frame

In [6]:
# getting stock price data in a data frame format

import yfinance as yf
from datetime import datetime, timedelta

# تعریف نماد سهام تسلا
ticker = "AAPL"

# محاسبه تاریخ 4 ماه پیش
end_date = datetime.now()
start_date = end_date - timedelta(days=120)

# غیرفعال کردن پراکسی
data=yf.download('AAPL',start=start_date,end=end_date)
data

C:\Users\fardi\AppData\Local\Temp\ipykernel_11044\1577755279.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data=yf.download('AAPL',start=start_date,end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-03-24  220.440918  221.189936  218.293740  220.710569  44299500
2025-03-25  223.456970  223.806518  219.791778  220.480877  34493600
2025-03-26  221.239868  224.725303  220.181259  223.217271  34466100
2025-03-27  223.556839  224.695345  220.271139  221.100054  37094800
2025-03-28  217.614624  223.516888  217.394911  221.379691  39818600
...                ...         ...         ...         ...       ...
2025-07-15  209.110001  211.889999  208.919998  209.220001  42296300
2025-07-16  210.160004  212.399994  208.639999  210.300003  47490500
2025-07-17  210.020004  211.800003  209.589996  210.570007  48068100
2025-07-18  211.179993  211.789993  209.699997  210.869995  48939500
2025-07-21  214.360001  215.779999  211.640900  212.050003  21045146

[82 rows x 5 columns]

In [15]:
import numpy as np
import talib

open = np.array(data['Open'], dtype=float)
close = np.array(data['Close'], dtype=float)
high = np.array(data['High'], dtype=float)
low = np.array(data['Low'], dtype=float)

high = high.flatten()
low = low.flatten()
close=close.flatten()
open=open.flatten()

talib.CDLENGULFING(open,high,low,close)
s
data["CDLENGULFING"]=talib.CDLENGULFING(open,high,low,close)
data

Price,Close,High,Low,Open,Volume,CDLENGULFING
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,
Date,,,,,,
2025-03-24,220.440918,221.189936,218.293740,220.710569,44299500,0
2025-03-25,223.456970,223.806518,219.791778,220.480877,34493600,0
2025-03-26,221.239868,224.725303,220.181259,223.217271,34466100,0
2025-03-27,223.556839,224.695345,220.271139,221.100054,37094800,100
2025-03-28,217.614624,223.516888,217.394911,221.379691,39818600,0
...,...,...,...,...,...,...
2025-07-15,209.110001,211.889999,208.919998,209.220001,42296300,0
2025-07-16,210.160004,212.399994,208.639999,210.300003,47490500,0
2025-07-17,210.020004,211.800003,209.589996,210.570007,48068100,0
2025-07-18,211.179993,211.789993,209.699997,210.869995,48939500,0
2025-07-21,214.360001,215.779999,211.640900,212.050003,21045146,0